//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrodieTheatre.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startMinimized {
            get {
                return ((bool)(this["startMinimized"]));
            }
            set {
                this["startMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.0.0.142")]
        public string harmonyHubIP {
            get {
                return ((string)(this["harmonyHubIP"]));
            }
            set {
                this["harmonyHubIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int potsPausedLevel {
            get {
                return ((int)(this["potsPausedLevel"]));
            }
            set {
                this["potsPausedLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42.22.B8")]
        public string potsAddress {
            get {
                return ((string)(this["potsAddress"]));
            }
            set {
                this["potsAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42.20.F8")]
        public string trayAddress {
            get {
                return ((string)(this["trayAddress"]));
            }
            set {
                this["trayAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plmPort {
            get {
                return ((string)(this["plmPort"]));
            }
            set {
                this["plmPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int trayPausedLevel {
            get {
                return ((int)(this["trayPausedLevel"]));
            }
            set {
                this["trayPausedLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int trayStoppedLevel {
            get {
                return ((int)(this["trayStoppedLevel"]));
            }
            set {
                this["trayStoppedLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int potsStoppedLevel {
            get {
                return ((int)(this["potsStoppedLevel"]));
            }
            set {
                this["potsStoppedLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int trayEnteringLevel {
            get {
                return ((int)(this["trayEnteringLevel"]));
            }
            set {
                this["trayEnteringLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int potsEnteringLevel {
            get {
                return ((int)(this["potsEnteringLevel"]));
            }
            set {
                this["potsEnteringLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string projectorPort {
            get {
                return ((string)(this["projectorPort"]));
            }
            set {
                this["projectorPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41.66.88")]
        public string motionSensorAddress {
            get {
                return ((string)(this["motionSensorAddress"]));
            }
            set {
                this["motionSensorAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9090")]
        public int kodiJSONPort {
            get {
                return ((int)(this["kodiJSONPort"]));
            }
            set {
                this["kodiJSONPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41.58.FC")]
        public string doorSensorAddress {
            get {
                return ((string)(this["doorSensorAddress"]));
            }
            set {
                this["doorSensorAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int insteonMotionLatch {
            get {
                return ((int)(this["insteonMotionLatch"]));
            }
            set {
                this["insteonMotionLatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int lightingDelayProjectorOn {
            get {
                return ((int)(this["lightingDelayProjectorOn"]));
            }
            set {
                this["lightingDelayProjectorOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int potsPlaybackLevel {
            get {
                return ((int)(this["potsPlaybackLevel"]));
            }
            set {
                this["potsPlaybackLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int trayPlaybackLevel {
            get {
                return ((int)(this["trayPlaybackLevel"]));
            }
            set {
                this["trayPlaybackLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int shutdownLatch {
            get {
                return ((int)(this["shutdownLatch"]));
            }
            set {
                this["shutdownLatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool connectKodiLocalhost {
            get {
                return ((bool)(this["connectKodiLocalhost"]));
            }
            set {
                this["connectKodiLocalhost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string projectorARSetting1 {
            get {
                return ((string)(this["projectorARSetting1"]));
            }
            set {
                this["projectorARSetting1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string projectorARSetting2 {
            get {
                return ((string)(this["projectorARSetting2"]));
            }
            set {
                this["projectorARSetting2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string projectorARSetting3 {
            get {
                return ((string)(this["projectorARSetting3"]));
            }
            set {
                this["projectorARSetting3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string projectorARSetting4 {
            get {
                return ((string)(this["projectorARSetting4"]));
            }
            set {
                this["projectorARSetting4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string projectorARSetting5 {
            get {
                return ((string)(this["projectorARSetting5"]));
            }
            set {
                this["projectorARSetting5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.10")]
        public decimal projectorARRangeHigh1 {
            get {
                return ((decimal)(this["projectorARRangeHigh1"]));
            }
            set {
                this["projectorARRangeHigh1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.11")]
        public string projectorARRangeLow2 {
            get {
                return ((string)(this["projectorARRangeLow2"]));
            }
            set {
                this["projectorARRangeLow2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.00")]
        public decimal projectorARRangeHigh2 {
            get {
                return ((decimal)(this["projectorARRangeHigh2"]));
            }
            set {
                this["projectorARRangeHigh2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.01")]
        public string projectorARRangeLow3 {
            get {
                return ((string)(this["projectorARRangeLow3"]));
            }
            set {
                this["projectorARRangeLow3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.20")]
        public decimal projectorARRangeHigh3 {
            get {
                return ((decimal)(this["projectorARRangeHigh3"]));
            }
            set {
                this["projectorARRangeHigh3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.21")]
        public string projectorARRangeLow4 {
            get {
                return ((string)(this["projectorARRangeLow4"]));
            }
            set {
                this["projectorARRangeLow4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.30")]
        public decimal projectorARRangeHigh4 {
            get {
                return ((decimal)(this["projectorARRangeHigh4"]));
            }
            set {
                this["projectorARRangeHigh4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.31")]
        public string projectorARRangeLow5 {
            get {
                return ((string)(this["projectorARRangeLow5"]));
            }
            set {
                this["projectorARRangeLow5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.00")]
        public decimal projectorARRangeHigh5 {
            get {
                return ((decimal)(this["projectorARRangeHigh5"]));
            }
            set {
                this["projectorARRangeHigh5"] = value;
            }
        }
    }
}
